definitions:
  app.CollectDefectsDTO:
    properties:
      component:
        type: string
      issue_id:
        type: string
      score:
        type: string
      status:
        type: string
      version:
        type: string
    type: object
  controller.bulletinRequest:
    properties:
      issue_number:
        items:
          type: string
        type: array
    required:
    - issue_number
    type: object
info:
  contact: {}
paths:
  /v1/defect:
    get:
      consumes:
      - application/json
      description: collect information of some defects
      parameters:
      - description: collect defects after the date
        in: query
        name: date
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/app.CollectDefectsDTO'
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
      summary: collect information of some defects
      tags:
      - Defect
  /v1/defect/bulletin:
    post:
      consumes:
      - application/json
      description: generate security bulletin for some defects
      parameters:
      - description: body of some issue number
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/controller.bulletinRequest'
      responses:
        "201":
          description: Created
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: generate security bulletin for some defects
      tags:
      - Defect
swagger: "2.0"
